### ISSUE TITLE
Поддержка Oracle

### ISSUE THREAD

**Issue by jeypatronum** [thinking-home/migrator#8]
Доброго дня!
Прочитал вашу статью на pvsm.ru, было весьма интересно, решили попробовать применить у себя =)
В качестве клиента для Oracle  в рамках Core, неплохой заменой может послужить продукт DevArt.
В контексте одной библиотеки покрывает версии с 8 по 12.  
У себя в рамках компании успешно оттестировали его для весьма самобытной сборки 9i, все работает как часы.
Единственным выявленным расхождением от интерфейсов родной библиотеки оказался DbType.Blob в стандартной =  DbType.Lob для DevArt. В остальном же, при переходе со стандартного клиента, просто заменили в шапке строчку using и более ничего менять не пришлось, всё штатно заработало, попробуйте, вдруг чем поможет =) 
Спасибо за труд!

**Comment by dima117** [comment]
Добрый день! Извините, я только недавно увидел ваше сообщение.

Я добавил поддержку Oracle и опубликовал версию 3.2. Заодно добавил поддержку `netstandard2.1`.

Судя по дате вашего сообщения, вам эта функциональность уже не нужна, но, может быть, пригодится кому-нибудь другому.
