### ISSUE TITLE
Обработка типов defaultValue для столбца

### ISSUE THREAD

**Issue by KuJIT** [thinking-home/migrator#9]
Здравствуйте. Судя по всему, при задании defaultValue для столбца не учитывается ни тип столбца, ни тип значения по умолчанию. Например, если создавать столбец типа DbType.Double и передать в конструктор значение по умолчанию типа double, то сгенерируется запрос вида 

```sql
ALTER TABLE "schema"."tablename" ADD COLUMN "columnname" float8 DEFAULT 23,33
```
(проблема в запятой в качестве разделителя десятичной части)

Т.е. при задании значения по умолчанию, нужно заранее приводить это значение к строковому типу в правильном формате, что не очень удобно

Это планируется менять?

**Comment by dima117** [comment]
Добрый день! Кажется, автоматическое универсальное (для всех возможных типов) приведение значения делать сложно и нецелесообразно. Кроме того, может быть нужно задать значение не константой, а результатом вызова функции (например в mssql можно использовать `NEWID()`, чтобы сгенерировать новый `Guid`)

 Пожалуйста, считайте, что этот параметр принимает строку — SQL выражение для значения колонки по умолчанию.
